--- #YAML:1.0
name:               App-cpanoutdated
version:            0.14
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPAN::DistnameInfo:   0.1
    ExtUtils::MakeMaker:  6.56
    IO::Zlib:             0
    local::lib:           1.006008
    LWP:                  0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
