---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-cpanoutdated
no_index:
  directory:
    - t
    - inc
requires:
  CPAN::DistnameInfo: 0.1
  ExtUtils::MakeMaker: 6.56
  IO::Zlib: 0
  LWP: 0
  local::lib: 1.006008
  perl: 5.008001
  version: 0
version: 0.19
